"""Shared data contract for the interlayer pipeline.

This module is the ROOT of the dependency graph: it imports nothing from
``interlayer`` and every other module imports from it. It must stay free of
I/O, network access and heavy dependencies.

Stability rules for Wave 2 build agents:
  * Do NOT edit this file. If a field is missing, raise it with the scaffold
    owner rather than editing in place -- six agents share these definitions.
  * Every model is frozen (hashable, immutable). Build new instances with
    ``model_copy(update=...)`` instead of mutating.
  * Every artifact model carries ``schema_version``; bump ``SCHEMA_VERSION``
    only via the scaffold owner.
"""

from __future__ import annotations

import hashlib
import re
import unicodedata
from datetime import date, datetime
from enum import StrEnum
from typing import Annotated, Any, Literal, Self

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    NonNegativeFloat,
    NonNegativeInt,
    field_validator,
    model_validator,
)

SCHEMA_VERSION = "1.0.0"

__all__ = [
    "SCHEMA_VERSION",
    "Affiliation",
    "AffiliationKind",
    "ApproxDate",
    "Base",
    "Cluster",
    "Connection",
    "Education",
    "EvidenceItem",
    "GraphEdge",
    "GraphNode",
    "GraphStats",
    "MatchVerdict",
    "MutualObservation",
    "Org",
    "OrgKind",
    "Person",
    "Position",
    "Provenance",
    "RunManifest",
    "ScoreComponents",
    "ScoredCluster",
    "ScoredPerson",
    "Seniority",
    "TargetFirm",
    "TargetPerson",
    "UnresolvedMutual",
    "normalize_key",
    "stable_id",
    "stable_id_exact",
]


# --------------------------------------------------------------------------
# id + normalisation helpers (deterministic; no randomness, no clock)
# --------------------------------------------------------------------------

_WS_RE = re.compile(r"\s+")
_PUNCT_RE = re.compile(r"[^\w\s&+]", flags=re.UNICODE)


def normalize_key(value: str) -> str:
    """Fold a raw string to a comparison key.

    Deterministic and locale-independent: NFKD-fold, strip accents, lowercase,
    drop punctuation (keeping ``&`` and ``+``), collapse whitespace.

    >>> normalize_key("  Jane Street Capital, L.L.C. ")
    'jane street capital l l c'
    """
    folded = unicodedata.normalize("NFKD", value)
    folded = "".join(c for c in folded if not unicodedata.combining(c))
    folded = _PUNCT_RE.sub(" ", folded.casefold())
    return _WS_RE.sub(" ", folded).strip()


def stable_id(kind: str, *parts: str | None) -> str:
    """Content-addressed id: ``<kind>_<16 hex>``.

    Stable across processes and runs (BLAKE2b, not ``hash()``), so every stage
    derives the same id for the same entity without a shared counter.

    Parts are folded with :func:`normalize_key` first, which casefolds. That is
    right for names and employer strings, where case is presentation. It is wrong
    for opaque identifiers — use :func:`stable_id_exact` for those.
    """
    payload = "\x1f".join([kind, *(normalize_key(p) if p else "" for p in parts)])
    digest = hashlib.blake2b(payload.encode("utf-8"), digest_size=8).hexdigest()
    return f"{kind}_{digest}"


def stable_id_exact(kind: str, *parts: str | None) -> str:
    """Content-addressed id over parts taken **verbatim**, without folding.

    For opaque identifiers where case carries meaning. LinkedIn member URNs
    (``/in/ACoAAB…``) are the motivating case: casefolding them merges two
    distinct people into one record.
    """
    payload = "\x1f".join([kind, *((p or "") for p in parts)])
    digest = hashlib.blake2b(payload.encode("utf-8"), digest_size=8).hexdigest()
    return f"{kind}_exact_{digest}"


# --------------------------------------------------------------------------
# enums
# --------------------------------------------------------------------------


class OrgKind(StrEnum):
    COMPANY = "company"
    SCHOOL = "school"
    UNKNOWN = "unknown"


class AffiliationKind(StrEnum):
    EMPLOYMENT = "employment"
    EDUCATION = "education"


class Provenance(StrEnum):
    """How a claim came to exist.

    ``OBSERVED`` means a human read it off LinkedIn's own UI (a mutual-connections
    list). ``INFERRED`` means this tool derived it from affiliation evidence and it
    may be wrong. The report must never present INFERRED as fact.
    """

    OBSERVED = "observed"
    INFERRED = "inferred"


class MatchVerdict(StrEnum):
    """Outcome of resolving a raw employer/school string to a target firm."""

    ACCEPT = "accept"
    REVIEW = "review"
    REJECT = "reject"


class Seniority(StrEnum):
    INTERN = "intern"
    JUNIOR = "junior"
    MID = "mid"
    SENIOR = "senior"
    LEAD = "lead"
    EXECUTIVE = "executive"
    FOUNDER = "founder"
    UNKNOWN = "unknown"


class TargetFirm(StrEnum):
    """Target firms.

    Citadel LLC (the hedge fund) and Citadel Securities (the market maker) are
    SEPARATE COMPANIES with separate LinkedIn pages and separate staff. Merging
    them corrupts every downstream result, so they are distinct members here and
    there is deliberately no bare ``CITADEL``.
    """

    JANE_STREET = "jane_street"
    CITADEL_LLC = "citadel_llc"
    CITADEL_SECURITIES = "citadel_securities"


# --------------------------------------------------------------------------
# base
# --------------------------------------------------------------------------


class Base(BaseModel):
    """Frozen, strict-ish base for every contract model."""

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
        str_strip_whitespace=True,
        validate_assignment=True,
        use_enum_values=False,
        ser_json_timedelta="iso8601",
    )


class ApproxDate(Base):
    """LinkedIn dates are coarse: ``2019``, ``Jan 2019`` or a full date."""

    year: Annotated[int, Field(ge=1900, le=2100)]
    month: Annotated[int | None, Field(ge=1, le=12)] = None
    day: Annotated[int | None, Field(ge=1, le=31)] = None

    @model_validator(mode="after")
    def _day_requires_month(self) -> Self:
        if self.day is not None and self.month is None:
            raise ValueError("day given without month")
        return self

    @property
    def sort_key(self) -> int:
        """Monotone integer for ordering; missing parts sort to the start."""
        return self.year * 10_000 + (self.month or 0) * 100 + (self.day or 0)

    @property
    def span_start(self) -> int:
        """First instant this date could mean.

        A coarse LinkedIn date names a period, not a moment: ``2019`` means all
        of 2019. Treating it as 2019-01-01 for both ends of a comparison makes a
        real overlap disappear, so spans are compared, not points.
        """
        return self.year * 10_000 + (self.month or 1) * 100 + (self.day or 1)

    @property
    def span_end(self) -> int:
        """Last instant this date could mean: year-end, month-end, or the day."""
        if self.month is None:
            return self.year * 10_000 + 12 * 100 + 31
        if self.day is None:
            return self.year * 10_000 + self.month * 100 + 31
        return self.year * 10_000 + self.month * 100 + self.day

    def to_date(self) -> date:
        """Concrete date, defaulting missing month/day to January 1st."""
        return date(self.year, self.month or 1, self.day or 1)

    def __str__(self) -> str:
        if self.month is None:
            return f"{self.year:04d}"
        if self.day is None:
            return f"{self.year:04d}-{self.month:02d}"
        return f"{self.year:04d}-{self.month:02d}-{self.day:02d}"


# --------------------------------------------------------------------------
# entities
# --------------------------------------------------------------------------


class Org(Base):
    """A canonical company or school, after normalisation/alias resolution."""

    org_id: str
    name: str
    kind: OrgKind = OrgKind.UNKNOWN
    aliases: tuple[str, ...] = ()
    linkedin_url: str | None = None
    domain: str | None = None
    is_target: bool = False
    target_firm: TargetFirm | None = None

    @classmethod
    def make(cls, name: str, kind: OrgKind = OrgKind.UNKNOWN, **kw: Any) -> Org:
        return cls(org_id=stable_id("org", name), name=name, kind=kind, **kw)

    @model_validator(mode="after")
    def _target_consistency(self) -> Self:
        if self.is_target and self.target_firm is None:
            raise ValueError("is_target=True requires target_firm")
        return self


class Position(Base):
    """One employment stint. ``company_raw`` is verbatim from the export."""

    company_raw: str
    company_org_id: str | None = None
    title_raw: str = ""
    seniority: Seniority = Seniority.UNKNOWN
    start: ApproxDate | None = None
    end: ApproxDate | None = None
    is_current: bool = False

    @model_validator(mode="after")
    def _ordered(self) -> Self:
        if self.start and self.end and self.end.sort_key < self.start.sort_key:
            raise ValueError("position end precedes start")
        if self.is_current and self.end is not None:
            raise ValueError("is_current=True conflicts with an end date")
        return self


class Education(Base):
    school_raw: str
    school_org_id: str | None = None
    degree: str | None = None
    field_of_study: str | None = None
    start: ApproxDate | None = None
    end: ApproxDate | None = None

    @model_validator(mode="after")
    def _ordered(self) -> Self:
        if self.start and self.end and self.end.sort_key < self.start.sort_key:
            raise ValueError("education end precedes start")
        return self


class Person(Base):
    """A node in the network. ``person_id`` is content-addressed."""

    person_id: str
    first_name: str = ""
    last_name: str = ""
    full_name: str
    headline: str | None = None
    linkedin_url: str | None = None
    linkedin_slug: str | None = None
    email: str | None = None
    location: str | None = None
    positions: tuple[Position, ...] = ()
    educations: tuple[Education, ...] = ()
    is_ego: bool = False
    source: Literal["connections_csv", "enrichment", "manual", "synthetic"] = "connections_csv"

    @field_validator("linkedin_url")
    @classmethod
    def _strip_query(cls, v: str | None) -> str | None:
        return v.split("?", 1)[0].rstrip("/") if v else v

    @classmethod
    def make(cls, first_name: str, last_name: str, **kw: Any) -> Person:
        """Build with a deterministic id derived from name + slug/email."""
        slug = kw.get("linkedin_slug")
        url = kw.get("linkedin_url")
        if slug is None and url:
            slug = url.split("?", 1)[0].rstrip("/").rsplit("/", 1)[-1] or None
            kw["linkedin_slug"] = slug
        full = " ".join(p for p in (first_name, last_name) if p).strip()
        # A slug is an opaque identifier, so it is hashed verbatim; the email and
        # name fallbacks are presentation strings and are folded.
        pid = stable_id_exact("p", slug) if slug else stable_id("p", kw.get("email") or full)
        return cls(
            person_id=pid,
            first_name=first_name,
            last_name=last_name,
            full_name=kw.pop("full_name", full),
            **kw,
        )

    @property
    def current_company(self) -> str | None:
        for p in self.positions:
            if p.is_current:
                return p.company_raw
        return self.positions[0].company_raw if self.positions else None


class Connection(Base):
    """An ego-network edge: the user is connected to ``person_id``."""

    person_id: str
    connected_on: date | None = None
    degree: Literal[1, 2] = 1
    note: str | None = None


class Affiliation(Base):
    """Bipartite person->org edge; the substrate the graph is built from."""

    person_id: str
    org_id: str
    kind: AffiliationKind
    title: str | None = None
    seniority: Seniority = Seniority.UNKNOWN
    start: ApproxDate | None = None
    end: ApproxDate | None = None
    is_current: bool = False
    """Still there. Distinct from an unrecorded end date, which is merely unknown:
    two people both currently at a firm genuinely overlap and must not be damped
    as though their dates were missing."""

    weight: NonNegativeFloat = 1.0

    @property
    def affiliation_id(self) -> str:
        return stable_id("aff", self.person_id, self.org_id, str(self.kind), str(self.start or ""))

    def overlaps(self, other: Affiliation) -> bool:
        """True when two affiliations share an org and their date spans intersect.

        Compares spans rather than points. A year-only ``2019`` covers the whole
        of 2019, so it overlaps ``2019-06`` to ``2020``; comparing both ends at
        2019-01-01 would report no overlap and silently drop a real seven-month
        co-tenure.

        An affiliation marked current has no end, which is different from an end
        that was never recorded, though both are open on the right here.
        """
        if self.org_id != other.org_id:
            return False
        a0 = self.start.span_start if self.start else 0
        a1 = self.end.span_end if self.end else 99_999_999
        b0 = other.start.span_start if other.start else 0
        b1 = other.end.span_end if other.end else 99_999_999
        return a0 <= b1 and b0 <= a1


class TargetPerson(Base):
    """An employee of a target firm, reachable at 2nd degree from the ego.

    Collected by hand from a company People tab filtered to 2nd degree. Never
    scraped: this model exists to hold what a human read.
    """

    target_person_id: str
    full_name: str
    firm: TargetFirm
    linkedin_url: str | None = None
    linkedin_slug: str | None = None
    title_raw: str = ""
    seniority: Seniority = Seniority.UNKNOWN
    mutual_count: NonNegativeInt | None = None

    @field_validator("linkedin_url")
    @classmethod
    def _strip_query(cls, v: str | None) -> str | None:
        """Match Person's normalisation. An asymmetry here is a determinism trap:
        the same profile would round-trip differently depending on which model
        held it."""
        return v.split("?", 1)[0].rstrip("/") if v else v

    @classmethod
    def make(cls, full_name: str, firm: TargetFirm, **kw: Any) -> TargetPerson:
        slug = kw.get("linkedin_slug")
        url = kw.get("linkedin_url")
        if slug is None and url:
            slug = url.split("?", 1)[0].rstrip("/").rsplit("/", 1)[-1] or None
            kw["linkedin_slug"] = slug
        return cls(
            target_person_id=(
                stable_id_exact("t", slug, str(firm))
                if slug
                else stable_id("t", full_name, str(firm))
            ),
            full_name=full_name,
            firm=firm,
            **kw,
        )


class MutualObservation(Base):
    """A human-recorded mutual-connections reading: TRUE edges, not inference.

    ``{ego's connections} INTERSECT {target's connections}`` is exactly what
    LinkedIn renders on a 2nd-degree profile. Each ``bridge_person_id`` is a
    connection of the ego who is provably also connected to ``target_person_id``.

    ``complete`` records whether the human saw the whole list or hit pagination /
    truncation; an incomplete reading may not be treated as an exhaustive set.
    """

    target_person_id: str
    bridge_person_ids: tuple[str, ...] = ()
    observed_on: date | None = None
    stated_count: NonNegativeInt | None = None
    complete: bool = True
    note: str | None = None
    provenance: Literal[Provenance.OBSERVED] = Provenance.OBSERVED

    @model_validator(mode="after")
    def _sorted_unique(self) -> Self:
        uniq = tuple(sorted(set(self.bridge_person_ids)))
        if uniq != self.bridge_person_ids:
            object.__setattr__(self, "bridge_person_ids", uniq)
        return self

    @property
    def truncated(self) -> bool:
        """True when the human saw fewer names than LinkedIn claimed existed."""
        return self.stated_count is not None and len(self.bridge_person_ids) < self.stated_count


class UnresolvedMutual(Base):
    """A name the operator recorded that could not be tied to a known person.

    Surfaced rather than dropped: a mutual connection this tool failed to match
    is a gap in the operator's picture, and silently discarding it would present
    an incomplete result as a complete one.
    """

    raw_text: str
    target_person_id: str | None = None
    reason: Literal["no_match", "ambiguous_name", "not_a_connection", "malformed"] = "no_match"
    candidates: tuple[str, ...] = ()
    hint: str | None = None
    source_line: NonNegativeInt | None = None


# --------------------------------------------------------------------------
# graph
# --------------------------------------------------------------------------


class GraphNode(Base):
    person_id: str
    label: str
    degree: NonNegativeInt = 0
    cluster_id: str | None = None
    attrs: dict[str, Any] = Field(default_factory=dict)


class GraphEdge(Base):
    """Undirected person-person edge; ``source < target`` is enforced."""

    source: str
    target: str
    weight: NonNegativeFloat = 1.0
    shared_org_ids: tuple[str, ...] = ()
    kinds: tuple[AffiliationKind, ...] = ()
    provenance: Provenance = Provenance.INFERRED
    """Set by the graph stage. Recorded rather than re-derived, because two
    stages independently guessing whether an edge is an observed bridge will
    eventually disagree."""

    @model_validator(mode="after")
    def _canonical_orientation(self) -> Self:
        if self.source == self.target:
            raise ValueError("self-loops are not allowed")
        if self.source > self.target:
            lo, hi = self.target, self.source
            object.__setattr__(self, "source", lo)
            object.__setattr__(self, "target", hi)
        return self

    @property
    def edge_id(self) -> str:
        return stable_id("e", self.source, self.target)


class GraphStats(Base):
    n_nodes: NonNegativeInt = 0
    n_edges: NonNegativeInt = 0
    n_components: NonNegativeInt = 0
    density: NonNegativeFloat = 0.0
    modularity: float | None = None


# --------------------------------------------------------------------------
# clustering + scoring
# --------------------------------------------------------------------------


class Cluster(Base):
    cluster_id: str
    label: str = ""
    member_ids: tuple[str, ...] = ()
    top_orgs: tuple[tuple[str, int], ...] = ()
    top_titles: tuple[tuple[str, int], ...] = ()
    cohesion: NonNegativeFloat = 0.0
    algorithm: str = "leiden"
    resolution: float = 1.0

    @property
    def size(self) -> int:
        return len(self.member_ids)


class EvidenceItem(Base):
    """Why a score moved. Rendered verbatim in the report -- keep it human."""

    kind: Literal[
        "observed_mutual",
        "direct_employment",
        "past_employment",
        "shared_employer",
        "shared_school",
        "cluster_membership",
        "title_signal",
        "path_proximity",
    ]
    detail: str
    contribution: float = 0.0
    org_id: str | None = None
    via_person_id: str | None = None
    hops: NonNegativeInt | None = None
    provenance: Provenance = Provenance.INFERRED

    @model_validator(mode="after")
    def _observed_only_for_mutuals(self) -> Self:
        if self.provenance is Provenance.OBSERVED and self.kind != "observed_mutual":
            raise ValueError(
                f"provenance=observed is only valid for kind='observed_mutual', got {self.kind!r}"
            )
        return self


class ScoreComponents(Base):
    """Additive components; ``total`` is their sum, weights live in config."""

    direct: float = 0.0
    alumni: float = 0.0
    proximity: float = 0.0
    cluster: float = 0.0
    title: float = 0.0

    @property
    def total(self) -> float:
        return round(self.direct + self.alumni + self.proximity + self.cluster + self.title, 6)


class ScoredPerson(Base):
    person_id: str
    full_name: str
    score: float
    rank: NonNegativeInt = 0
    components: ScoreComponents = Field(default_factory=ScoreComponents)
    per_firm: dict[TargetFirm, float] = Field(default_factory=dict)
    cluster_id: str | None = None
    evidence: tuple[EvidenceItem, ...] = ()
    hops_to_target: NonNegativeInt | None = None

    @model_validator(mode="after")
    def _scored_requires_evidence(self) -> Self:
        """A non-zero score the operator cannot audit is a score they cannot act on."""
        if self.score != 0.0 and not self.evidence:
            raise ValueError(
                f"ScoredPerson {self.person_id!r} has score={self.score} but no evidence; "
                "every scored person must carry the evidence that moved the score"
            )
        return self

    @property
    def has_observed_evidence(self) -> bool:
        """True when at least one evidence item is a real mutual-connection reading."""
        return any(e.provenance is Provenance.OBSERVED for e in self.evidence)


class ScoredCluster(Base):
    cluster_id: str
    label: str
    score: float
    rank: NonNegativeInt = 0
    size: NonNegativeInt = 0
    target_density: NonNegativeFloat = 0.0
    per_firm: dict[TargetFirm, float] = Field(default_factory=dict)
    top_person_ids: tuple[str, ...] = ()
    rationale: str = ""


# --------------------------------------------------------------------------
# run metadata (determinism / provenance)
# --------------------------------------------------------------------------


class RunManifest(Base):
    """Written next to every artifact set so a run can be reproduced."""

    schema_version: str = SCHEMA_VERSION
    run_id: str
    created_at: datetime
    seed: int = 20240101
    tool_version: str = "0.1.0"
    python_version: str = ""
    input_sha256: str | None = None
    input_filename: str | None = None
    stage_versions: dict[str, str] = Field(default_factory=dict)
    config_sha256: str | None = None
    counts: dict[str, int] = Field(default_factory=dict)
