# (query_string, expected_target_key)  expected None => must NOT match any target
CASES = [
    # --- Jane Street true positives ---
    ("Jane Street", "jane_street"),
    ("Jane Street Capital", "jane_street"),
    ("Jane Street Capital, LLC", "jane_street"),
    ("Jane Street Group", "jane_street"),
    ("Jane Street Group, LLC", "jane_street"),
    ("JANE STREET GROUP LLC", "jane_street"),
    ("jane street", "jane_street"),
    ("Jane  Street   Capital", "jane_street"),
    ("Jane Street Europe", "jane_street"),
    ("Jane Street Financial Limited", "jane_street"),
    ("Jane Street Financial Ltd.", "jane_street"),
    ("Jane Street Netherlands B.V.", "jane_street"),
    ("Jane Street Asia Trading Limited", "jane_street"),
    ("Jane Street Hong Kong Limited", "jane_street"),
    ("Jane Street Singapore Pte. Ltd.", "jane_street"),
    ("Jane Street Execution Services, LLC", "jane_street"),
    ("Jane St.", "jane_street"),
    ("JaneStreet", "jane_street"),
    ("Jane-Street", "jane_street"),
    ("Jane Street (JS)", "jane_street"),
    ("Jane Street​ Capital", "jane_street"),   # nbsp + zero width
    ("ＪＡＮＥ　ＳＴＲＥＥＴ", "jane_street"),              # fullwidth NFKC
    # --- Jane Street true negatives ---
    ("Jane Street Coffee", None),
    ("Jane Street Entertainment", None),
    ("Jane Street Dental Practice", None),
    ("123 Jane Street Bakery", None),
    ("Mary Jane Street Foods", None),
    ("Jane Street Studios Toronto", None),
    ("Janestreet Realty of Toronto", None),
    # --- Citadel LLC (fund) true positives ---
    ("Citadel", "citadel_llc"),
    ("Citadel LLC", "citadel_llc"),
    ("Citadel | Chicago", "citadel_llc"),
    ("Citadel Advisors LLC", "citadel_llc"),
    ("Citadel Enterprise Americas LLC", "citadel_llc"),
    ("Citadel Investment Group", "citadel_llc"),
    ("Surveyor Capital (A Citadel Company)", "citadel_llc"),
    ("Ashler Capital (A Citadel Company)", "citadel_llc"),
    ("Citadel Global Equities", "citadel_llc"),
    ("CITADEL  llc", "citadel_llc"),
    # --- Citadel Securities true positives ---
    ("Citadel Securities", "citadel_securities"),
    ("Citadel Securities LLC", "citadel_securities"),
    ("Citadel Securities Europe Limited", "citadel_securities"),
    ("CITADEL SECURITIES (EUROPE) LIMITED", "citadel_securities"),
    ("Citadel Securities LP", "citadel_securities"),
    ("Citadel Securities GCS (Ireland) Limited", "citadel_securities"),
    # --- Citadel true negatives (the money cases) ---
    ("The Citadel", None),
    ("The Citadel, The Military College of South Carolina", None),
    ("Citadel Military College of South Carolina", None),
    ("The Citadel Alumni Association", None),
    ("The Citadel School of Engineering", None),
    ("Citadel Broadcasting", None),
    ("Citadel Broadcasting Corporation", None),
    ("Citadel Communications", None),
    ("Citadel Credit Union", None),
    ("Citadel Federal Credit Union", None),
    ("Citadel Defense Company", None),
    ("Citadel Servicing Corporation", None),
    ("Citadel Servicing Corp / Acra Lending", None),
    ("The Citadel Group", None),
    ("Citadel Group Australia", None),
    ("Citadel Security Software", None),
    ("Citadel Insurance Services", None),
    ("Citadel Salisbury", None),
    ("Citadel Bank", None),
    ("Citadel Mall", None),
    ("Citadelle Distillery", None),
    ("La Citadelle", None),
    # --- other adjacent quant firms (should map to themselves, not to JS/Citadel) ---
    ("Two Sigma Investments", "two_sigma"),
    ("Hudson River Trading", "hrt"),
    ("HRT", "hrt"),
    ("Jump Trading", "jump"),
    ("D. E. Shaw & Co.", "de_shaw"),
    ("The D. E. Shaw Group", "de_shaw"),
    ("Optiver", "optiver"),
    ("IMC Trading", "imc"),
    ("Susquehanna International Group", "sig"),
    ("SIG Susquehanna", "sig"),
    ("Virtu Financial", "virtu"),
    ("Millennium Management", "millennium"),
    ("Point72 Asset Management", "point72"),
    ("Point 72", "point72"),
    # --- cross-firm confusable negatives ---
    ("Two Sigma Ventures", "two_sigma"),
    ("Sigma Software", None),
    ("Jump Capital", None),
    ("IMC Financial Markets", "imc"),
    ("SIG Sauer", None),
    ("SIG Group AG", None),
    ("Virtu Health", None),
    ("Millennium Physician Group", None),
    ("Millennium Trust Company", None),
    ("Hudson River Community Credit Union", None),
    ("Hudson Bay Capital", None),
    ("Shaw Communications", None),
    ("Optiver Australia", "optiver"),
]
